heat_template_version: 2021-04-16

description: >
  This template deploys a network, a subnet, a router, and an Ubuntu instancewithin the created network,
  and configures external connectivity for the router.

resources:
  my_network:
    type: OS::Neutron::Net
    properties:
      name: MyInitialNetwork

  my_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: my_network }
      cidr: 192.168.10.0/24
      name: MyInitialSubnet-v5
  
  my_router:
    type: OS::Neutron::Router
    properties:
      name: MyFirstRouter

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
        router: { get_resource: my_router }
        subnet: { get_resource: my_subnet }

   ubuntu_instance:
    type: OS::Nova::Server
    properties:
      name: MyUbuntuVm
      image: Ubuntu Server 24.04 LTS (Noble Numbat) amd64
      flavor: gx3.1c4r
      networks:
        - network: { get_resource: my_network }

outputs:
  ubuntu_instance_ip:
    description: The IP address of the deployed Ubuntu instance