apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: testingdockerimage.azurecr.io/idata2502_exam:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: acr-secret
