name: CI/CD to AKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: testingdockerimage.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t testingdockerimage.azurecr.io/idata2502_exam:latest .
          docker push testingdockerimage.azurecr.io/idata2502_exam:latest

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/deployment.yaml
            manifests/service.yaml
          namespace: default
          images: testingdockerimage.azurecr.io/idata2502_exam:latest
